config/routes.rb
Rails.application.routes.draw do
   root 'app#index'

  resources :users do
    resources :exercises
  end

  resources :users do
    resources :workouts
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
  has_many :workouts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :exercises
  has_many :workouts

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :user_name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercises
  belongs_to :user

end

app/controllers/app_controller.rb
class AppController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include ApplicationHelper
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @exercises = current_user.exercises
    @name = current_user.user_name

    if @exercises
      render json: @exercises
    else
      render status: 400, nothing: true
    end
  end

  def show
    @exercise = Exercise.find(params[:id])

    if @exercise
      render json: @exercise
    else
      render status: 400, nothing: true
    end
  end

  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      render json: @exercise
    else
      render status: 400, nothing: true
    end
  end

  def update
    @exercise = exercise.find(params[:id])

    if @exercise.update(exercise_params)
      render json: @exercise
    else
      render status: 400, nothing: true
    end
  end

  def destroy
    @exercise = exercise.find(params[:id])

    if @exercise.destroy
      render json: {}
    else
      render status: 400, nothing: true
    end
  end

  private

  def exercise_params
    params.require(:exercise).permit(:ex_name, :two_sides?, :reps, :img_url, :holdtime, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user_path(user)
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  # respond_to :html, :json

  def new
    @user = User.new
  end

  def create
    user = User.find_by(params[:id])

    @user = User.new(user_params)
    if @user.save
      sign_in @user
      binding.pry
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :user_name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = current_user.workouts
    @name = current_user.user_name

    if @workouts
      render json: @workouts
    else
      render status: 400, nothing: true
    end
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      render json: @workout
    else
      render status: 400, nothing: true
    end
  end

  def destroy
    @workout = workout.find(params[:id])

    if @workout.destroy
      render json: {}
    else
      render status: 400, nothing: true
    end
  end

    private

  def workout_params
    params.require(:workout).permit(:user_id, :exercise_id, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Signin Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security Checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end
end

app/views/app/index.html.erb
<div class="container">
  <div class="bg"></div>
  <div class="jumbotron">

    <h1>PT Helper</h1>

    <p>Need help managing your physical therapy routine? Give <b>PT Helper</b> a try!</p>

    <%= link_to "Sign In", signin_path, class: "btn btn-large btn-info" %>
    <%= link_to "Sign up", signup_path, class: "btn btn-large btn-info" %>

    <% if signed_in? %>
      <%= current_user.id %>
    <% end %>

  </div>
</div>

app/views/common/_signout.html.erb
<% if signed_in? %>
  <%= form_for :session, url: signout_path, method: 'delete', class: 'navbar-form' do |f| %>
    <%= f.submit "Sign out", id: 'signout', class: 'btn-sm' %>
  <% end %>
<% else %>
  <%= link_to "Sign In", signin_path %>
  <%= link_to "Sign up", signup_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PT Helper</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
    <body>
      <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    </body>
</html>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit", id: 'submit', class: 'btn btn-success' %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit <%= @user.user_name %></h1>
  <%= render "user_form" %>

  <hr>

  <%= form_for @user, method: 'delete' do |f| %>
    <%= f.submit "Delete" %>
  <% end %>

  <hr>

  <%= link_to "Cancel", @user %>
</div>

app/views/users/new.html.erb
<div class="container">
  <%= link_to "Back", root_url %>
  <h1>Sign Up</h1>
  <%= render "user_form" %>
</div>

app/views/users/show.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <ul class="navbar navbar-default navbar-fixed-top nav-pills nav-justified" role="tablist">
    <li><a class="brand navbar-text active" href="#account-info">PT Helper</a></li>
    <li><a class="navbar-text" href="#new-exercise">Add New Exercise</a></li>
    <li><a class="navbar-text" href="#exercise-list">My Exercises</a></li>
    <li><a class="navbar-text" href="#workout-history">Activity Log</a></li>
    <li><a class="navbar-text"><%= render 'common/signout' %></a></li>
  </ul>
</div>

<div class="container">

    <div class="view" id="account-info"></div>
      <script type="template" id="account-info-template">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <h1>Manage Account</h1>
            <ul>
              <li>View Messages</li>
              <li>Edit User Settings</li>
            </ul>
          </div>
        </div>
      </script>


    <ul class="view list-group" id="exercise-list"></ul>
    <script type="template" id="exercise-list-template">
      <div class="row">
        <div class="col-md-2"></div>
          <div class="col-md-6">
            <h1>Assigned Exercises</h1>
            <%% exerciseCollection.each(function(exercise) { %>
              <div class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" src="<%%= exercise.get('img_url') %>" alt="">
                </a>
                <div class="media-body">
                  <h4 class="media-heading pull-left"><%%= exercise.get('ex_name') %></h4>
                  <button class="btn pull-right btn-sm btn-primary destroy">Remove</button>
                <a class="btn pull-right btn-sm btn-primary" href="#exercises/<%%= exercise.get('id')%>">View</a>
                </div>
              </div>
              </li>
            <%% }) %>
          </div>
      </div>
    </script>

    <form class="view" id="new-exercise"></form>
    <script type="template" id="new-exercise-template">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-6">
          <div class="input-group">
          <fieldset>
            <h2>Enter New Exercise</h2>
              <label>Exercise Name</label>
                <input id="exercise-name" type="text" name="ex_name"><br/>
              <label>Left And Right Sides?</label>
                <input id="left-right" type="checkbox" name="two_sides" value=true><br/>
              <label>Number of Reps</label>
                <input id="reps" type="integer" name="reps"><br/>
              <label>Image Link</label>
                <input id="img_url" type="text" name="img_url"><br/>
              <label>Hold Position for... (seconds)</label>
                <input id="holdtime" type="integer" name="holdtime"><br/>
                <input type="hidden" name="user_id" value="<%= current_user.id %>">
            <input type="submit" class="btn btn-success" value="Submit">
          </fieldset>
          </div>
        </div>
        <div class="col-md-4">
          <h2>Current Assigned Exercises</h2>
          <%% exerciseCollection.each(function(exercise) { %>
            <li><%%= exercise.get('ex_name') %></li>
          <%% }) %>
        </div>
      </div>
    </script>

    <div class="view" id="workout-timer"></div>
    <script type="template" id="workout-timer-template">
      <div class="row">
        <div class="col-md-2"></div>

            <div class="col-md-4">
              <h1><%%= model.get('ex_name') %></h1>
              <form class="exComplete bg-warning">
                <p class="">Save this exercise?</p>
                <input type="hidden" name="user_id" value="<%= current_user.id %>">
                <input type="hidden" name="exercise_id" value="<%%= model.get('id') %>">
                <input type="hidden" name="completed?" value=true>
                <input type="submit" class="btn" value="Yes">
                <input type="button" class="btn" value="No">
              </form>
              <input type="button" class="start btn btn-success" id="watch" value="Start" />
                <ul>
                  <li class="side extimer"><b>Left</b></li>
                  <li class="extimer">Time to Hold:<span class="hold"><%%= model.get('holdtime') %></span></li>
                  <li class="extimer">Number of Reps:<span class="reps"><%%= model.get('reps') %></span></li>
            </div>
            <div class="col-md-4">
                  <li class="extimer"><img class="demo img-responsive" alt="" src="<%%= model.get('img_url') %>"></li>
            </div>
                </ul>
        </div>
    </script>

    <div class="view" id="workout-history"></div>
      <script type="template" id="workout-history-template">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <h1>Workout History</h1>
            <%% workoutCollection.each(function(exercise) { %>
              <li>
                Ex. number: <%%= exercise.get('exercise_id') %>
                Completed at: <%%= exercise.get('created_at') %>
              </li>
            <%% }) %>
          </div>
        </div>
      </script>

<!--
              <input type="file" capture="camera" accept="image/*" id="img_url" name="img_url">

 --></div>